In [4]:
import tensorflow as tf
import tensorflow.keras as keras

## One-Hot Encoding

In [10]:
vocab = ["<1H OCEAN", "INLAND", "NEAR OCEAN", "NEAR BAY", "ISLAND"]
indices = tf.range(len(vocab), dtype=tf.int64)
table_init = tf.lookup.KeyValueTensorInitializer(vocab, indices)
table_init

In [13]:
for s in dir(table_init):
    if not s.startswith("_"):
        print(s)

initialize
key_dtype
value_dtype


In [14]:
n_oov_buckets = 2
table = tf.lookup.StaticVocabularyTable(table_init, n_oov_buckets)
table

In [15]:
for s in dir(table):
    if not s.startswith("_"):
        print(s)

key_dtype
lookup
name
resource_handle
size
value_dtype


## Embeddings


### Manually
- randomly initialized
- one row per category and per oov bucket
- one column per embedding dimension

In [8]:
embedding_dim = 2
embedding_init = tf.random.uniform([len(vocab) + n_oov_buckets, embedding_dim])
embedding_init

<tf.Tensor: shape=(7, 2), dtype=float32, numpy=
array([[0.25670135, 0.9297389 ],
       [0.7387067 , 0.45911717],
       [0.04919159, 0.49531627],
       [0.03997183, 0.7775849 ],
       [0.24492908, 0.6916243 ],
       [0.78538704, 0.30175245],
       [0.9321128 , 0.6056347 ]], dtype=float32)>

In [9]:
embedding_matrix = tf.Variable(embedding_init)
embedding_matrix

<tf.Variable 'Variable:0' shape=(7, 2) dtype=float32, numpy=
array([[0.25670135, 0.9297389 ],
       [0.7387067 , 0.45911717],
       [0.04919159, 0.49531627],
       [0.03997183, 0.7775849 ],
       [0.24492908, 0.6916243 ],
       [0.78538704, 0.30175245],
       [0.9321128 , 0.6056347 ]], dtype=float32)>