In [1]:
def cube(x):
    return x**3

In [2]:
cube(2), cube(2.0)

(8, 8.0)

In [5]:
from IPython.core.display import HTML
# Prevent ligatures like "ff", etc
HTML("""
    <style>
    body { font-feature-settings: "liga" 0; }
    </style>
""")

In [6]:
import tensorflow as tf

In [7]:
cube(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [8]:
tf_cube_ = tf.function(cube)
tf_cube_

In [11]:
tf_cube_(2), tf_cube_(2.0), tf_cube_(2.), tf_cube_(2.00), tf_cube_(2.1)

(<tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.261>)

**Rmk.** This seems to be bad: The `dtype` is not loyally or easily reflected.

In [12]:
tf_cube_(tf.constant(2)), tf_cube_(tf.constant(2.0))

(<tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=float32, numpy=8.0>)

In [15]:
[attr for attr in dir(tf_cube_) if not attr.startswith("_")]

['experimental_get_compiler_ir',
 'experimental_get_tracing_count',
 'function_spec',
 'get_concrete_function',
 'get_initialization_function',
 'input_signature',
 'pretty_printed_concrete_signatures',
 'python_function']

In [17]:
tf_cube_.python_function(2), tf_cube_.python_function(2.0)

(8, 8.0)

In [18]:
@tf.function
def tf_cube(x):
    return x**3

In [22]:
tf_cube

In [19]:
tf_cube(2), tf_cube(2.0), tf_cube(2.), tf_cube(2.00), tf_cube(2.1)

(<tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.261>)

In [20]:
tf_cube(float(2.0))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

Hmmm, so, it's the same problem of `dtype` whether we use a decorator `@tf.funtion` or we use `tf.function()`.

In [21]:
tf.__version__

'2.4.1'